apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mentoraschool-tls-cert
spec:
  secretName: mentoraschool-tls
  dnsNames:
    - www.mentoraschool.com
    - school.mentoragroupe.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

# Note: If you are testing, use a staging issuer (e.g. letsencrypt-staging) to avoid rate limits.